# Psiriroon Dark Theme

# SYNTAX

# Color mappings:
# background -> white
# foreground -> black
#
# normal     -> foreground
# comment    -> cyan
# constant   -> lime
# variable   -> blue
# function   -> yellow
# type       -> purple

"attribute" = "lime"
"type" = "purple"
"constructor" = "purple"
"constant" = "lime"
"string" = "lime"
"comment" = { fg = "cyan", bg = "t_cyan", modifiers = ["italic"] }
"variable" = "blue"
"label" = "white"
"punctuation" = "silver"
"keyword" = "white"
"operator" = "white"
"function" = "orange"
"tag" = "gray"
"namespace" = "white"
"special" = "white"
# TODO: add markup section

# DIAGNOSTICS
# Gutter
"hint" = "silver"
"info" = "white"
"warning" = "yellow"
"error" = "red"

# Inline
"diagnostic" = "white"
"diagnostic.hint" = "silver"
"diagnostic.info" = "white"
"diagnostic.warning" = { fg = "yellow", underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { fg = "red", underline = { color = "red", style = "curl" }, modifiers = ["bold"] }
"diagnostic.unecessary" = "gray"
"diagnostic.deprecated" = { modifiers = ["crossed-out"] }

# DIFF
"diff.plus" = { fg = "green", bg = "t_green" }
"diff.minus" = { fg = "red", bg = "t_red" }
"diff.delta" = { fg = "blue", bg = "t_blue" }

# UI
"ui.background" = { bg = "black" }
"ui.background.separator" = "gray"

"ui.cursor" = { fg = "black", bg = "blue" }
"ui.cursor.normal" = { fg = "black", bg = "blue" }
"ui.cursor.insert" = { fg = "black", bg = "green" }
"ui.cursor.select" = { fg = "black", bg = "yellow" }
"ui.cursor.match" = { fg = "black", bg = "silver" }

"ui.debug.breakpoint" = { fg = "purple" }
"ui.debug.active" = { fg = "magenta"  }

"ui.gutter" = { bg = "black" }
"ui.gutter.selected" = { bg = "black" }

"ui.linenr" = "silver"
"ui.linenr.selected" = "white"

"ui.statusline" = { fg = "white", bg = "gray" }
"ui.statusline.inactive" = { fg = "silver", bg = "gray"}
"ui.statusline.normal" = { fg = "white", bg = "blue" }
"ui.statusline.insert" = { fg = "white", bg = "green" }
"ui.statusline.select" = { fg = "white", bg = "yellow" }
"ui.statusline.separator" = "silver"

"ui.bufferline" = { fg = "white", bg = "gray" }
"ui.bufferline.active" = { fg = "black", bg = "white" }
"ui.bufferline.background" = { fg = "black", bg = "gray" }

"ui.popup" = { fg = "white", bg = "ash" }
"ui.popup.info" = { fg = "white", bg = "ash" }

"ui.help" = { fg = "white", bg = "ash" }

"ui.text" = "white"
"ui.text.focus" = { underline = { color = "white", style = "line" } }
"ui.text.inactive" = "silver"
"ui.text.info" = "white"

"ui.virtual.indent-guide" = "gray"
"ui.virtual.wrap" = "gray"

"ui.menu" = { fg = "white", bg = "ash" }
"ui.menu.selected" = { underline = { color = "white", style = "line" } }

"ui.selection" = { bg = "t_blue" }

# PALETTE
[palette]
# Basic
"black" = "#0E1019"
"ash" = "#232323"
"gray" = "#5A5A5A"
"silver" = "#9C9C9C"
"white" = "#FFFAF4"

"red" = "#FF000F"
"magenta" = "#E67BF7"
"purple" = "#9A5FEB"
"blue" = "#0092FF"
"sky" = "#4DBCFF"
"cyan" = "#00D8EB"
"green" = "#0EB75B"
"lime" = "#8CE10B"
"yellow" = "#FFB900"
"orange" = "#F87810"

# Translucent (25% opacity over background) colors
"t_red" = "#870814"
"t_blue" = "#07518C"
"t_cyan" = "#0B424E"
"t_green" = "#0E643A"

